name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install deps
      run: |
        python --m pip install --upgrade pip
        pip install 

    - name: Install any missing pip dependencies
      run: |
        python -m pip install -r requirements.txt
      # Only use this step if you have extra pip dependencies not in your environment.yml

    - name: Test with pytest
      run: |
        python -m pytest
